### ISSUE TITLE
Configurable search collection and profile parameters

### ISSUE THREAD

**Issue by jortronQGov** [qld-gov-au/qgds-qol-mvp#184]
ForGov uses its own Funnelback search collection and profile (`collection=qgov~sp-forgov` and `profile=forgov`). 

Could these parameters be exposed as configurable options in the JSON data?

https://github.com/qld-gov-au/qgds-qol-mvp/blob/834e7be9621c6686acfb7378e0f3ee70e43ce42f/src/components/bs5/header/header.functions.js#L92-L93

https://github.com/qld-gov-au/qgds-qol-mvp/blob/834e7be9621c6686acfb7378e0f3ee70e43ce42f/src/components/bs5/header/header.functions.js#L159

https://github.com/qld-gov-au/qgds-qol-mvp/blob/834e7be9621c6686acfb7378e0f3ee70e43ce42f/src/components/bs5/header/header.functions.js#L187

**Comment by MitchAnderson93** [comment]
Will be resolved in next PR via custom data tags on generic search input

**Comment by jortronQGov** [comment]
Awesome! Thanks Mitch 🙂
